name=AMRFID
version=1.0.1
author=Guilherme Caiala
maintainer=guicaiala@gmail.com
sentence=Camada de abstração sobre MFRC522 para leitura RFID simplificada.
paragraph=Separa claramente leitura, validação e ação. Suporta lista configurável de cartões autorizados e callbacks personalizados para acesso permitido e negado.
category=Communication
url=https://github.com/guicaiala/AMRFID
architectures=*
depends=MFRC522
